# Generated by Django 3.1.1 on 2020-10-01 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OkulSınav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sınıf', models.IntegerField()),
                ('şube', models.CharField(max_length=10)),
                ('matematik', models.TextField(blank=True, default='{}', null=True)),
                ('fizik', models.TextField(blank=True, default='{}', null=True)),
                ('kimya', models.TextField(blank=True, default='{}', null=True)),
                ('biyoloji', models.TextField(blank=True, default='{}', null=True)),
                ('türk_dili', models.TextField(blank=True, default='{}', null=True)),
                ('edebiyat', models.TextField(blank=True, default='{}', null=True)),
                ('sosyal', models.TextField(blank=True, default='{}', null=True)),
                ('cografya', models.TextField(blank=True, default='{}', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Okul Sınavları',
            },
        ),
    ]
