# Generated by Django 2.2.4 on 2021-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_excelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelform',
            name='sınıf',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelform',
            name='şube',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
