# Generated by Django 2.2.4 on 2021-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210224_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelform',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
