# Generated by Django 2.2.4 on 2021-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210321_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okulsınav',
            name='user',
        ),
        migrations.AddField(
            model_name='okulsınav',
            name='isim_soyisim',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okulsınav',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excelform',
            name='sınıf',
            field=models.CharField(max_length=10),
        ),
    ]
