# Generated by Django 3.0.5 on 2020-07-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='öğretmen',
            name='no',
        ),
    ]
