# Generated by Django 3.0.5 on 2020-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_yoklama_kurum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sınıf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_programı', models.TextField()),
                ('yoklama', models.TextField()),
                ('başarı', models.IntegerField()),
                ('no', models.IntegerField()),
                ('ödev', models.TextField()),
                ('hocalar', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='yoklama',
            name='kurum',
        ),
    ]
