# Generated by Django 3.0.5 on 2020-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_öğretmen_etüt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğretmen',
            name='etüt',
            field=models.TextField(default='{}'),
        ),
    ]
