# Generated by Django 3.0.5 on 2020-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200813_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='öğretmen',
            name='etüt',
        ),
    ]
