# Generated by Django 3.0.5 on 2020-08-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_etüt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sınıf',
        ),
    ]
