# Generated by Django 3.1.1 on 2020-09-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0011_auto_20200822_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ÖğretmendProgramı',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('öğretmen', models.CharField(max_length=20)),
                ('ders', models.CharField(max_length=20)),
                ('pazartesi', models.TextField(default='{}')),
                ('salı', models.TextField(default='{}')),
                ('çarşamba', models.TextField(default='{}')),
                ('perşembe', models.TextField(default='{}')),
                ('cuma', models.TextField(default='{}')),
                ('cumartesi', models.TextField(default='{}')),
                ('pazar', models.TextField(default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ders Programları',
            },
        ),
    ]
