# Generated by Django 3.1.1 on 2020-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_öğretmendprogramı'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğretmendprogramı',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
