# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20200913_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='öğretmen',
            name='profil_foto',
            field=models.FileField(null=True, upload_to='', validators=[teacher.models.file_control]),
        ),
    ]
