# Generated by Django 2.2.4 on 2020-09-23 11:50

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_öğretmen_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğretmen',
            name='profil_foto',
            field=models.FileField(default='default.jpg', null=True, upload_to='', validators=[teacher.models.file_control]),
        ),
    ]
