# Generated by Django 3.1.1 on 2020-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20200930_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğretmen',
            name='etüt_saatleri',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
