# Generated by Django 2.2.4 on 2021-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_auto_20200930_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='öğretmendprogramı',
            name='sınıflar',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
