# Generated by Django 2.2.4 on 2021-03-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_öğretmendprogramı_sınıflar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='öğretmendprogramı',
            name='sınıflar',
        ),
    ]
