# Generated by Django 2.2.4 on 2021-03-20 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_remove_öğretmendprogramı_sınıflar'),
    ]

    operations = [
        migrations.AddField(
            model_name='öğretmen',
            name='kayıttarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
