# Generated by Django 3.0.5 on 2020-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_ödev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ödev',
            name='bitiş_tarihi',
            field=models.DateField(),
        ),
    ]
