# Generated by Django 2.2.4 on 2020-09-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200923_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ödev',
            old_name='image_field',
            new_name='teacher_image',
        ),
    ]
