# Generated by Django 3.1.1 on 2020-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200923_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='ödev',
            name='şube',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
