# Generated by Django 3.1.1 on 2020-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_ödev_şube'),
    ]

    operations = [
        migrations.AddField(
            model_name='ödev',
            name='açıklama',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
