# Generated by Django 2.2.4 on 2020-11-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_ödev_açıklama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ödev',
            old_name='açıklama',
            new_name='acıklama',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='başlangıç_tarihi',
            new_name='baslangic_tarihi',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='başlık',
            new_name='baslik',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='bitiş_tarihi',
            new_name='bitis_tarihi',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='içerik',
            new_name='icerik',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='öğretmen',
            new_name='ogretmen',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='sınıf',
            new_name='sinif',
        ),
        migrations.RenameField(
            model_name='ödev',
            old_name='şube',
            new_name='sube',
        ),
    ]
