# Generated by Django 2.2.4 on 2020-11-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201104_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ödev',
            old_name='acıklama',
            new_name='aciklama',
        ),
    ]
