# Generated by Django 2.2.4 on 2021-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201104_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoklama',
            name='sınıf',
            field=models.CharField(max_length=20),
        ),
    ]
