# Generated by Django 2.2.4 on 2021-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20210310_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoklama',
            name='geç_gelenler',
            field=models.CharField(default=[1283], max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yoklama',
            name='izinliler',
            field=models.CharField(default=[1283], max_length=300),
            preserve_default=False,
        ),
    ]
