# Generated by Django 2.2.4 on 2021-03-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20210310_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yoklama',
            old_name='dersaralığı',
            new_name='derssaati',
        ),
    ]
