# Generated by Django 2.2.4 on 2021-03-14 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0016_auto_20210314_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoklama',
            name='user',
            field=models.ForeignKey(default=102, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
