# Generated by Django 2.2.4 on 2021-03-14 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_yoklama_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoklama',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
