# Generated by Django 2.2.4 on 2021-03-14 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20210314_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoklama',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
