# Generated by Django 3.0.5 on 2020-07-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhasebe',
            name='asgari_ödeme',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
