# Generated by Django 3.0.5 on 2020-07-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0002_muhasebe_asgari_ödeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhasebe',
            name='asgari_ödeme',
            field=models.CharField(max_length=1000),
        ),
    ]
