# Generated by Django 3.0.5 on 2020-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0003_auto_20200723_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhasebe',
            name='k_taksit_adedi',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
