# Generated by Django 3.0.5 on 2020-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0004_muhasebe_k_taksit_adedi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muhasebe',
            name='asgari_ödeme',
        ),
        migrations.AddField(
            model_name='muhasebe',
            name='ödenecek_miktar',
            field=models.IntegerField(default=400),
            preserve_default=False,
        ),
    ]
