# Generated by Django 3.0.5 on 2020-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0005_auto_20200723_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhasebe',
            name='k_taksit_adedi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='taksit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='taksit_adedi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='taksit_günü',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='ödenecek_miktar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='ödenen_miktar',
            field=models.PositiveIntegerField(),
        ),
    ]
