# Generated by Django 3.0.5 on 2020-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0006_auto_20200723_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhasebe',
            name='k_taksit_adedi',
            field=models.IntegerField(),
        ),
    ]
