# Generated by Django 3.0.5 on 2020-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0007_auto_20200723_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhasebe',
            name='ödenme_zamanları',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
