# Generated by Django 3.0.5 on 2020-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0013_auto_20200723_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhasebe',
            name='ödenemiş_ay',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
