# Generated by Django 3.0.5 on 2020-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0014_muhasebe_ödenemiş_ay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhasebe',
            name='ödenemiş_ay',
            field=models.IntegerField(null=True),
        ),
    ]
