# Generated by Django 3.0.5 on 2020-07-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0015_auto_20200724_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muhasebe',
            old_name='ödenemiş_ay',
            new_name='ödenmemiş_ay',
        ),
    ]
