# Generated by Django 3.0.5 on 2020-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0016_auto_20200724_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhasebe',
            name='borçlu_mu',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muhasebe',
            name='tamamlandı_mı',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
