# Generated by Django 3.0.5 on 2020-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0017_auto_20200724_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhasebe',
            name='borçlu_mu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='tamamlandı_mı',
            field=models.BooleanField(default=False),
        ),
    ]
