# Generated by Django 3.0.5 on 2020-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0018_auto_20200724_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhasebe',
            name='k_taksit_adedi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='taksit_adedi',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='ödeme_geçmişi',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='ödenecek_miktar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='muhasebe',
            name='ödenen_miktar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
