# Generated by Django 3.0.5 on 2020-08-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0019_auto_20200724_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muhasebe',
            options={'verbose_name_plural': 'Muhasebeler'},
        ),
    ]
