# Generated by Django 3.0.5 on 2020-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_duyuru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duyuru',
            old_name='gönderen',
            new_name='oluşturan',
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
