# Generated by Django 3.0.5 on 2020-08-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_duyuru_check_tarih'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duyuru',
            options={'verbose_name_plural': 'Duyurular'},
        ),
        migrations.AlterModelOptions(
            name='etüt',
            options={'verbose_name_plural': 'Etütler'},
        ),
        migrations.AlterModelOptions(
            name='yoklama',
            options={'verbose_name_plural': 'Yoklamalar'},
        ),
    ]
