# Generated by Django 3.0.5 on 2020-08-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_remove_duyuru_check_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='dosya',
            field=models.FileField(default='12', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DuyuruDosya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('duyuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Duyuru')),
            ],
        ),
    ]
