# Generated by Django 3.0.5 on 2020-08-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_remove_duyuru_dosya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyurudosya',
            name='duyuru',
        ),
    ]
