# Generated by Django 3.0.5 on 2020-08-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_duyurudosya_duyuru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyurudosya',
            name='duyuru',
        ),
    ]
