# Generated by Django 3.0.5 on 2020-08-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_duyurudosya_duyuru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuyuruDosya',
        ),
    ]
