# Generated by Django 3.0.5 on 2020-08-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20200831_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurudosya',
            name='duyuru',
            field=models.IntegerField(),
        ),
    ]
