# Generated by Django 3.0.5 on 2020-08-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20200831_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuyuruDosya',
        ),
    ]
