# Generated by Django 3.0.5 on 2020-09-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_duyurudosya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etüt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Yoklama',
        ),
        migrations.DeleteModel(
            name='Etüt',
        ),
    ]
