# Generated by Django 3.0.5 on 2020-09-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20200909_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duyurudosya',
            options={'verbose_name_plural': 'Duyuru Dosyaları'},
        ),
    ]
