# Generated by Django 3.0.5 on 2020-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_auto_20200909_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='dosya',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
