# Generated by Django 3.0.5 on 2020-09-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_duyuru_dosya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuyuruDosya',
        ),
    ]
