# Generated by Django 3.1.1 on 2020-09-18 20:35

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_auto_20200917_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[general.models.file_control]),
        ),
    ]
