# Generated by Django 3.1.1 on 2020-09-18 20:38

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_auto_20200918_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='dosya',
            field=models.FileField(null=True, upload_to='', validators=[general.models.file_control]),
        ),
    ]
