# Generated by Django 3.1.1 on 2020-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_duyuru_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='to',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
