# Generated by Django 3.1.1 on 2020-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_auto_20200920_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='to',
            field=models.CharField(default='666666', max_length=10),
        ),
    ]
