# Generated by Django 2.2.4 on 2020-09-23 09:33

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_auto_20200921_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[general.models.file_control]),
        ),
    ]
