# Generated by Django 2.2.4 on 2020-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_auto_20200923_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
