# Generated by Django 2.2.4 on 2020-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='username',
            field=models.CharField(default='jehat122', max_length=20),
            preserve_default=False,
        ),
    ]
