# Generated by Django 2.2.4 on 2020-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_auto_20200923_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='USERNAME_FIELD',
            field=models.CharField(max_length=20, verbose_name='username'),
        ),
    ]
