# Generated by Django 2.2.4 on 2020-09-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0034_auto_20200923_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
