# Generated by Django 3.0.5 on 2020-08-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20200717_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yönetici',
            options={'verbose_name_plural': 'Yöneticiler'},
        ),
    ]
