# Generated by Django 3.1.1 on 2020-09-30 18:29

import administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20200822_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='yönetici',
            name='profil_foto',
            field=models.FileField(default='default.jpg', null=True, upload_to='', validators=[administrator.models.file_control]),
        ),
    ]
