# Generated by Django 3.0.5 on 2020-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='sınavsonuçları',
            field=models.TextField(blank=True, null=True),
        ),
    ]
