# Generated by Django 3.0.5 on 2020-08-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200802_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='öğrenci',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='öğrenci',
            name='veli_tel',
            field=models.CharField(default='05366639292', max_length=20),
            preserve_default=False,
        ),
    ]
