# Generated by Django 3.0.5 on 2020-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200804_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ödev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('öğretmen', models.CharField(max_length=30)),
                ('ders', models.CharField(max_length=20)),
                ('başlangıç_tarihi', models.DateTimeField(auto_now_add=True)),
                ('bitiş_tarihi', models.DateField(auto_now_add=True)),
                ('başlık', models.TextField()),
                ('içerik', models.TextField()),
                ('yapanlar', models.TextField(default='{}')),
                ('yapmayanlar', models.TextField(default='{}')),
            ],
        ),
    ]
