# Generated by Django 3.0.5 on 2020-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_ödev'),
    ]

    operations = [
        migrations.AddField(
            model_name='ödev',
            name='sınıf',
            field=models.IntegerField(default=119),
            preserve_default=False,
        ),
    ]
