# Generated by Django 3.0.5 on 2020-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_ödev_sınıf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ödev',
            name='yapanlar',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='ödev',
            name='yapmayanlar',
            field=models.TextField(default='[]'),
        ),
    ]
