# Generated by Django 3.0.5 on 2020-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200820_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ödev',
            name='başlangıç_tarihi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
