# Generated by Django 3.0.5 on 2020-08-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200820_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ödev',
            options={'verbose_name_plural': 'Ödevler'},
        ),
        migrations.AlterModelOptions(
            name='öğrenci',
            options={'verbose_name_plural': 'Öğrenciler'},
        ),
    ]
