# Generated by Django 3.0.5 on 2020-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200822_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='sınavsonuçları',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
