# Generated by Django 3.0.5 on 2020-09-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_öğrenci_sınavsonuçları'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ödev',
        ),
    ]
