# Generated by Django 3.1.1 on 2020-09-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_öğrencidprogramı_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='öğrencidprogramı',
            name='ders',
        ),
    ]
