# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_öğrenci_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='profil_foto',
            field=models.FileField(null=True, upload_to='', validators=[student.models.file_control]),
        ),
    ]
