# Generated by Django 3.1.1 on 2020-09-30 19:23

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200917_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='profil_foto',
            field=models.FileField(default='default.jpg', null=True, upload_to='', validators=[student.models.file_control]),
        ),
    ]
