# Generated by Django 3.1.1 on 2020-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200930_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='öğrenci',
            name='şube',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
