# Generated by Django 2.2.4 on 2021-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_öğrenci_şube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='sınıf',
            field=models.CharField(max_length=10),
        ),
    ]
