# Generated by Django 2.2.4 on 2021-03-20 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20210318_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='öğrenci',
            name='kayıttarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
