# Generated by Django 2.2.4 on 2021-03-20 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_öğrenci_kayıttarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
