# Generated by Django 3.0.7 on 2020-07-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200711_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
